CREATE TABLE IF NOT EXISTS livros
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    ano_publicacao integer,
    autor varchar(80),
    editora varchar(80),
    isbn varchar(50),
    titulo varchar(80),
    disponivel boolean NOT NULL DEFAULT TRUE, -- ADICIONADO
    CONSTRAINT livros_pkey PRIMARY KEY (id)
);


CREATE TABLE IF NOT EXISTS usuarios
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    nome varchar(80),
    password varchar(80),
    CONSTRAINT usuarios_pkey PRIMARY KEY (id)
);