CREATE TABLE IF NOT EXISTS emprestimo -- Nome da tabela conforme a entidade Emprestimo.java
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    livro_id bigint NOT NULL,
    usuario_id bigint NOT NULL,
    data_emprestimo date NOT NULL,
    data_devolucao_prevista date NOT NULL,
    data_devolucao_real date,
    CONSTRAINT emprestimo_pkey PRIMARY KEY (id),
    CONSTRAINT fk_emprestimo_livro FOREIGN KEY (livro_id)
    REFERENCES livros (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION,
    CONSTRAINT fk_emprestimo_usuario FOREIGN KEY (usuario_id)
    REFERENCES usuarios (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    );